### ISSUE TITLE
Adjustment coordinate scale

### ISSUE THREAD

**Issue by WeiWeiZong** [fusion-energy/openmc_cylindrical_mesh_plotter#24]
Hello, when I installed openmc_plot, my section did not appear contour level. I want to adjust the coordinate value of the color bar on the right. How should I do this?

**Comment by shimwell** [comment]
There is a ```colorbar_kwargs``` argument that might help. It accepts a dictionary that gets pass to colorbar. Perhaps try passing in vmin and vmax.

**Comment by WeiWeiZong** [comment]
Thank you for your answer. That really solved my problem. Thank you.

**Comment by shimwell** [comment]
Super thanks for letting me know.
